lists = [] #or lists = list()
lists.append(1)
lists.append(3)
lists.append(5)

lists.append("Book")
lists.append("Pencil")
lists.append("Laptop")
print("Lists length is ",len(lists))
print(lists)
print("Book" in lists)
print("Computer" in lists)
print("Pencil" in lists)
print(100 in lists)
